id: D8AC2621B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:46:40+00:00'
last_modified: '2022-05-27T14:59:50.387512+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    90b3:
      image_group_id: I1PD95908
      title: ལྟ་བ་ཐ་དད་པ་རྣམ་པར་ཕྱེ་བ་མདོར་བསྡུས་པ།
      total_pages: 1926
      order: 63
      base_file: 90b3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
