id: PB25A4FBB
initial_creation_type: ocr
source_metadata:
  volumes:
    8c5d953dc2e0479bb85ee986ad3ed973:
      base_file: v063.txt
      image_group_id: I1PD95908
      title: ལྟ་བ་ཐ་དད་པ་རྣམ་པར་ཕྱེ་བ་མདོར་བསྡུས་པ།
      total_pages: 1926
      volume_number: 63
